[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/spl-token",
]
exclude = [
    "programs/anchor-counter",
    "programs/stake-pool",
]

[programs.devnet]
# stake-pool = "8SXiV3EVddw8HLe1Hhz6aQJL12wq5CEXxqiZwLpWrxDA"
spl-token = "B1eH6keWuJZjoRLsP822HaiRWRWAgX7eqs9LZ7omA9YP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/spl-token.ts"


